@ECHO OFF
SETLOCAL

IF "%~1" == "" EXIT /B 2
SET CONFIGURATION=%~1
SET D=bin\%CONFIGURATION%\net6.0
CD /D "%~dp0"
%D%\Pard ..\Pard.Test\Parser422.y obj\Parser422.g.cs
IF NOT ERRORLEVEL 0 EXIT /B 0
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
CALL ..\%~nx0 %*
